### Configure a variable for the web service base address.
@base_address = https://localhost:7089/todo

### Insert a new Todo item.
POST {{base_address}}
Content-Type: application/json

{
  "title": "Buy groceries",
  "description": "Buy milk, eggs, and bread",
  "OwnerId": "1"
}

### New Id
@new_id = 1

### Get all posts.
GET {{base_address}}

### Get a post by Id.
GET {{base_address}}/{{new_id}}

### Update a post.
PUT {{base_address}}/{{new_id}}
Content-Type: application/json

{
  "title": "Buy groceries - updated",
  "description": "Buy milk, eggs, and bread"
}

### Delete a post.
DELETE {{base_address}}/{{new_id}}

### Get all posts.
GET {{base_address}}